const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('readingCompanion', {
  platform: process.platform,
  edition: process.argv.includes('--public-edition') ? 'public' : 'local',
  openPDFDialog: () => ipcRenderer.invoke('dialog:open-pdf'),
  openFolderDialog: () => ipcRenderer.invoke('dialog:open-folder'),
  readPDF: sourcePath => ipcRenderer.invoke('pdf:read', sourcePath),
  fileStat: target => ipcRenderer.invoke('file:stat', target),
  recognizeOCR: payload => ipcRenderer.invoke('ocr:recognize', payload),
  cancelOCR: jobId => ipcRenderer.invoke('ocr:cancel', jobId),
  onOCRProgress: callback => ipcRenderer.on('ocr:progress', (_event, payload) => callback(payload)),
  getInitialProject: () => ipcRenderer.invoke('project:initial'),
  onMenuOpenPDF: callback => ipcRenderer.on('menu:open-pdf', () => callback()),
  openProject: (sourcePath, currentPath) => ipcRenderer.invoke('project:open', { sourcePath, currentPath }),
  onOpenProjectInPlace: callback => ipcRenderer.on('project:open-in-place', (_event, sourcePath) => callback(sourcePath)),
  listProjects: () => ipcRenderer.invoke('project:list'),
  loadProject: sourcePath => ipcRenderer.invoke('project:load', sourcePath),
  saveProject: (sourcePath, state) => ipcRenderer.invoke('project:save', { sourcePath, state }),
  deleteProject: sourcePath => ipcRenderer.invoke('project:delete', sourcePath),
  loadDerived: sourcePath => ipcRenderer.invoke('derived:load', sourcePath),
  saveDerived: (sourcePath, value) => ipcRenderer.invoke('derived:save', { sourcePath, value }),
  loadSettings: () => ipcRenderer.invoke('settings:load'),
  saveSettings: settings => ipcRenderer.invoke('settings:save', settings),
  listModels: settings => ipcRenderer.invoke('ai:list-models', settings),
  detectProvider: apiKey => ipcRenderer.invoke('ai:detect-provider', apiKey),
  requestAI: request => ipcRenderer.invoke('ai:request', request),
  cancelAI: id => ipcRenderer.invoke('ai:cancel', id),
  onAIProgress: callback => ipcRenderer.on('ai:progress', (_event, payload) => callback(payload)),
  startSpeech: language => ipcRenderer.invoke('speech:start', language),
  stopSpeech: () => ipcRenderer.invoke('speech:stop'),
  onSpeech: callback => ipcRenderer.on('speech:result', (_event, payload) => callback(payload)),
  readClipboard: () => ipcRenderer.invoke('clipboard:read'),
  writeClipboard: text => ipcRenderer.invoke('clipboard:write', text),
  writeTextFile: (target, content) => ipcRenderer.invoke('file:write-text', { target, content }),
  readTextFile: target => ipcRenderer.invoke('file:read-text', target),
  pathExists: target => ipcRenderer.invoke('file:exists', target),
  openPath: target => ipcRenderer.invoke('shell:open-path', target),
  openExternal: target => ipcRenderer.invoke('shell:open-external', target),
  listObsidianVaults: () => ipcRenderer.invoke('obsidian:list-vaults'),
  resolveObsidianVault: candidate => ipcRenderer.invoke('obsidian:resolve-vault', candidate),
  openObsidianNote: (vaultPath, notePath) => ipcRenderer.invoke('obsidian:open-note', { vaultPath, notePath }),
  documentsPath: () => ipcRenderer.invoke('system:documents-path'),
  joinPath: (...parts) => ipcRenderer.invoke('system:join-path', parts),
  resourcePath: name => ipcRenderer.invoke('system:resource-path', name),
  sha256: value => ipcRenderer.invoke('system:sha256', value)
});
